# Generated by Django 2.1 on 2018-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('movie', models.IntegerField()),
                ('self_study', models.IntegerField()),
                ('lectures', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('went_out', models.IntegerField()),
                ('sleep', models.IntegerField()),
            ],
        ),
    ]
