# Generated by Django 2.1 on 2018-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uusers', '0002_auto_20180820_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('totMovie', models.IntegerField(default=0)),
                ('totStudy', models.IntegerField(default=0)),
                ('totLectures', models.IntegerField(default=0)),
                ('totExercise', models.IntegerField(default=0)),
                ('totWent', models.IntegerField(default=0)),
                ('totSleep', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('pie', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
