# Generated by Django 2.1 on 2018-08-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uusers', '0003_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='uusers.UserDetail'),
        ),
    ]
