# Generated by Django 2.1 on 2018-08-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uusers', '0005_remove_userdetail_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='logs',
            field=models.IntegerField(default=0),
        ),
    ]
