# Generated by Django 2.1 on 2018-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uusers', '0006_userdetail_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
