# Generated by Django 2.1 on 2018-08-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uusers', '0009_userdetail_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dp',
            field=models.FileField(default='default.jpeg', upload_to='.'),
        ),
    ]
